### ISSUE TITLE
Propensity Scoring

### ISSUE THREAD

**Issue by hamelsmu** [ntstevens/A-B-Testing-and-Beyond#1]
@ntstevens If you have any good recommendations for books, blogs, etc. on propensity scoring or other methods for inferring causality on observational data that would be excellent.

**Comment by ntstevens** [comment]
Hi Hamel,

-- [This](https://en.wikipedia.org/wiki/Propensity_score_matching) is the wikipedia article on propensity score matching, which is a relatively intuitive and non-technical introduction to PSM. 

-- [This](http://www.stat.cmu.edu/~ryantibs/journalclub/rosenbaum_1983.pdf) is the original paper by Rosenbaum and Rubin (1983) in which the idea was first proposed. It is more technical, but a good reference.

-- [This](http://sekhon.berkeley.edu/papers/MatchingJSS.pdf) is a paper by the creator of the "Matching" package in R which is useful for various kinds of matching (PSM included) for the purpose of estimating treatment effects in observational data.

I looked around for some tech blogs that discussed this, but came up empty. I also reached out to my past students that I mentioned did some causal inference with PSM at Mozilla. He said they are currently working on a white paper and a blog that he is willing to share when they are complete. I'll be sure to pass them along with they're ready. In the meantime, I hope you find these other resources helpful.

Nathaniel
